
language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/waiterdbtest
     
node_js:  
        - "8.9.4"
        
before_script:
  - psql -c 'create database waiterdbtest;' -U postgres
  - psql -U postgres -d waiterdbtest -a -f waiterdb.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2



